unbind r
bind r source-file ~/.tmux.conf

set -g prefix C-s

set -g mouse on

set -s set-clipboard on
set -g allow-passthrough on
set -as terminal-features ' ,xterm-kitty:hyperlinks:clipboard'

bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
